### Data wrangling

In [35]:
import pandas as pd

url = "https://raw.githubusercontent.com/chrisalbon/sim_data/master/titanic.csv"
df = pd.read_csv(url)
df.head()

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0

In [36]:
print("Dataframe shape:", df.shape)
df.describe()

Dataframe shape: (1313, 6)

              Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1313 entries, 0 to 1312
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      1313 non-null   str
 1   PClass    1313 non-null   str
 2   Age       756 non-null    float64
 3   Sex       1313 non-null   str
 4   Survived  1313 non-null   int64
 5   SexCode   1313 non-null   int64
dtypes: float64(1), int64(2), str(3)
memory usage: 61.7 KB

### Show first record

In [38]:
df.iloc[0]

Name        Allen, Miss Elisabeth Walton
PClass                               1st
Age                                 29.0
Sex                               female
Survived                               1
SexCode                                1
Name: 0, dtype: object

### 10 rows and 6 columns

In [39]:
df.iloc[0:10, 0:6]

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0
5,"Anderson, Mr Harry",1st,47.00,male,1,0
6,"Andrews, Miss Kornelia Theodosia",1st,63.00,female,1,1
7,"Andrews, Mr Thomas, jr",1st,39.00,male,0,0
8,"Appleton, Mrs Edward Dale (Charlotte Lamson)",1st,58.00,female,1,1
9,"Artagaveytia, Mr Ramon",1st,71.00,male,0,0

### Min, Max, Mean, Sum, Count

In [40]:
print('Maximum:', df['Age'].max())
print('Minimum:', df['Age'].min())
print('Mean:', df['Age'].mean())
print('Sum:', df['Age'].sum())
print('Count:', df['Age'].count())

Maximum: 71.0
Minimum: 0.17
Mean: 30.397989417989418
Sum: 22980.88
Count: 756

### Count of value by columns

In [41]:
df.count()

Name        1313
PClass      1313
Age          756
Sex         1313
Survived    1313
SexCode     1313
dtype: int64

### Count of male and female

In [42]:
df['Sex'].value_counts()

Sex
male      851
female    462
Name: count, dtype: int64

### Count of people in every class

In [43]:
df['PClass'].value_counts()

PClass
3rd    711
1st    322
2nd    279
*        1
Name: count, dtype: int64

### Find people without Age value

In [44]:
df[df['Age'].isnull()]

                              Name PClass  Age     Sex  Survived  SexCode
12    Aubert, Mrs Leontine Pauline    1st  NaN  female         1        1
13        Barkworth, Mr Algernon H    1st  NaN    male         1        0
14              Baumann, Mr John D    1st  NaN    male         0        0
29         Borebank, Mr John James    1st  NaN    male         0        0
32              Bradley, Mr George    1st  NaN    male         1        0
...                            ...    ...  ...     ...       ...      ...
1300         Wiseman, Mr Phillippe    3rd  NaN    male         0        0
1302             Yalsevac, Mr Ivan    3rd  NaN    male         1        0
1305            Youssef, Mr Gerios    3rd  NaN    male         0        0
1306           Zabour, Miss Hileni    3rd  NaN  female         0        1
1307           Zabour, Miss Tamini    3rd  NaN  female         0        1

[557 rows x 6 columns]

### Delete duplicates

In [45]:
df.drop_duplicates()

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0
...,...,...,...,...,...,...
1308,"Zakarian, Mr Artun",3rd,27.00,male,0,0
1309,"Zakarian, Mr Maprieder",3rd,26.00,male,0,0
1310,"Zenni, Mr Philip",3rd,22.00,male,0,0
1311,"Lievens, Mr Rene",3rd,24.00,male,0,0
1312,"Zimmerman, Leo",3rd,29.00,male,0,0

### Count of survived and not

In [46]:
survived_counts = df['Survived'].value_counts().sort_index()

print('Not Survived (0):', survived_counts.get(0, 0))
print('Survived (1):', survived_counts.get(1, 0))

Not Survived (0): 863
Survived (1): 450